site_name: Dynamic Cluster Assembly Framework (D-CAF)

theme:
  name: material

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths:
            - .
          options:
            members: null
            docstring_style: google
            members_order: source
            show_source: true
            show_submodules: false
            show_if_no_docstring: false
            show_root_heading: true
            show_symbol_type_heading: true
            filters: public
            summary:
              modules: true
              functions: true

  - api-autonav:
      modules:
        - dcaf
      nav_section_title: API Reference
      api_root_uri: reference
      nav_item_prefix : ""
      show_full_namespace: true

nav:
  - Home: index.md
  - Installation: install.md

extra_css:
   - stylesheets/api-reference.css
